export enum LOG_ACTION {
  // Movie related actions
  CREATE_MOVIE = 'CREATE_MOVIE',
  UPDATE_MOVIE = 'UPDATE_MOVIE',
  DELETE_MOVIE = 'DELETE_MOVIE',
  LIKE_MOVIE = 'LIKE_MOVIE',
  UNLIKE_MOVIE = 'UNLIKE_MOVIE',
  ADD_MOVIE_TO_WATCHLIST = 'ADD_MOVIE_TO_WATCHLIST',
  REMOVE_MOVIE_FROM_WATCHLIST = 'REMOVE_MOVIE_FROM_WATCHLIST',
  PLAY_MOVIE = 'PLAY_MOVIE',

  // Series related actions
  CREATE_SERIES = 'CREATE_SERIES',
  UPDATE_SERIES = 'UPDATE_SERIES',
  DELETE_SERIES = 'DELETE_SERIES',
  LIKE_SERIES = 'LIKE_SERIES',
  UNLIKE_SERIES = 'UNLIKE_SERIES',
  ADD_SERIES_TO_WATCHLIST = 'ADD_SERIES_TO_WATCHLIST',
  REMOVE_SERIES_FROM_WATCHLIST = 'REMOVE_SERIES_FROM_WATCHLIST',
  PLAY_EPISODE_OF_SERIES = 'PLAY_EPISODE_OF_SERIES',

  // User related actions
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  USER_REGISTRATION = 'USER_REGISTRATION',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  USER_BAN = 'USER_BAN',
  USER_UNBAN = 'USER_UNBAN',

  // review related actions
  CREATE_REVIEW = 'CREATE_REVIEW',
  UPDATE_REVIEW = 'UPDATE_REVIEW',
  DELETE_REVIEW = 'DELETE_REVIEW',

  // Actor related actions
  CREATE_ACTOR = 'CREATE_ACTOR',
  UPDATE_ACTOR = 'UPDATE_ACTOR',
  DELETE_ACTOR = 'DELETE_ACTOR',

  // Director related actions
  CREATE_DIRECTOR = 'CREATE_DIRECTOR',
  UPDATE_DIRECTOR = 'UPDATE_DIRECTOR',
  DELETE_DIRECTOR = 'DELETE_DIRECTOR',

  // Category related actions
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',

  // tag related actions
  CREATE_TAG = 'CREATE_TAG',
  UPDATE_TAG = 'UPDATE_TAG',
  DELETE_TAG = 'DELETE_TAG',

  // News related actions
  CREATE_NEWS = 'CREATE_NEWS',
  UPDATE_NEWS = 'UPDATE_NEWS',
  DELETE_NEWS = 'DELETE_NEWS',

  // Content related actions
  CONTENT_VIEW_INCREASED = 'CONTENT_VIEW_INCREASED',
}
